// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Adresa
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class AdresaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Adresa>
    {
        public AdresaConfiguration()
            : this("dbo")
        {
        }

        public AdresaConfiguration(string schema)
        {
            ToTable("Adresa", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Ulice).HasColumnName(@"Ulice").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Mesto).HasColumnName(@"Mesto").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Psc).HasColumnName(@"PSC").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(6);
            Property(x => x.Cp).HasColumnName(@"CP").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
