// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Destinace
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class Destinace
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public string Zeme { get; set; } // Zeme (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child Zajezdy where [Zajezdy].[ID_Destinace] point to this entity (FK_Zajezdy_Destinace)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Zajezdy> Zajezdy { get; set; } // Zajezdy.FK_Zajezdy_Destinace

        public Destinace()
        {
            Id = System.Guid.NewGuid();
            Zajezdy = new System.Collections.Generic.List<Zajezdy>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
