// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    public interface IDB_Model : System.IDisposable
    {
        System.Data.Entity.DbSet<Adresa> Adresa { get; set; } // Adresa
        System.Data.Entity.DbSet<Destinace> Destinace { get; set; } // Destinace
        System.Data.Entity.DbSet<Doprava> Doprava { get; set; } // Doprava
        System.Data.Entity.DbSet<Kategorie> Kategorie { get; set; } // Kategorie
        System.Data.Entity.DbSet<KontaktniUdaje> KontaktniUdaje { get; set; } // Kontaktni_udaje
        System.Data.Entity.DbSet<Pojisteni> Pojisteni { get; set; } // Pojisteni
        System.Data.Entity.DbSet<Pojistovny> Pojistovny { get; set; } // Pojistovny
        System.Data.Entity.DbSet<Pokoje> Pokoje { get; set; } // Pokoje
        System.Data.Entity.DbSet<Prilohy> Prilohy { get; set; } // Prilohy
        System.Data.Entity.DbSet<Rezervace> Rezervace { get; set; } // Rezervace
        System.Data.Entity.DbSet<Stravovani> Stravovani { get; set; } // Stravovani
        System.Data.Entity.DbSet<sys_DatabaseFirewallRules> sys_DatabaseFirewallRules { get; set; } // database_firewall_rules
        System.Data.Entity.DbSet<TypUbytovani> TypUbytovani { get; set; } // Typ_ubytovani
        System.Data.Entity.DbSet<TypZajezdu> TypZajezdu { get; set; } // Typ_zajezdu
        System.Data.Entity.DbSet<Ubytovani> Ubytovani { get; set; } // Ubytovani
        System.Data.Entity.DbSet<VazTZajezdTypZajezdu> VazTZajezdTypZajezdu { get; set; } // VazT_Zajezd_TypZajezdu
        System.Data.Entity.DbSet<VazTZakaznikZajezd> VazTZakaznikZajezd { get; set; } // VazT_Zakaznik_Zajezd
        System.Data.Entity.DbSet<Zajezdy> Zajezdy { get; set; } // Zajezdy
        System.Data.Entity.DbSet<Zakaznici> Zakaznici { get; set; } // Zakaznici

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
