// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Kontaktni_udaje
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class KontaktniUdajeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<KontaktniUdaje>
    {
        public KontaktniUdajeConfiguration()
            : this("dbo")
        {
        }

        public KontaktniUdajeConfiguration(string schema)
        {
            ToTable("Kontaktni_udaje", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Telefon).HasColumnName(@"Telefon").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
