// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Pojisteni
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class PojisteniConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Pojisteni>
    {
        public PojisteniConfiguration()
            : this("dbo")
        {
        }

        public PojisteniConfiguration(string schema)
        {
            ToTable("Pojisteni", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdPojistovna).HasColumnName(@"ID_Pojistovna").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Cena).HasColumnName(@"Cena").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Typ).HasColumnName(@"Typ").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);

            // Foreign keys
            HasRequired(a => a.Pojistovny).WithMany(b => b.Pojisteni).HasForeignKey(c => c.IdPojistovna).WillCascadeOnDelete(false); // FK_Pojisteni_Pojistovny
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
