// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Pokoje
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class PokojeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Pokoje>
    {
        public PokojeConfiguration()
            : this("dbo")
        {
        }

        public PokojeConfiguration(string schema)
        {
            ToTable("Pokoje", schema);
            HasKey(x => new { x.Id, x.IdUbytovani, x.Kapacita });

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdUbytovani).HasColumnName(@"ID_Ubytovani").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Kapacita).HasColumnName(@"Kapacita").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Popis).HasColumnName(@"Popis").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Ubytovani).WithMany(b => b.Pokoje).HasForeignKey(c => c.IdUbytovani).WillCascadeOnDelete(false); // FK_Pokoje_Ubytovani
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
