// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Prilohy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class Prilohy
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public byte[] Priloha { get; set; } // Priloha (Primary key) (length: 2147483647)
        public System.Guid IdUbytovani { get; set; } // ID_Ubytovani (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Ubytovani pointed by [Prilohy].([IdUbytovani]) (FK_Prilohy_Ubytovani)
        /// </summary>
        public virtual Ubytovani Ubytovani { get; set; } // FK_Prilohy_Ubytovani

        public Prilohy()
        {
            Id = System.Guid.NewGuid();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
