// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Prilohy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class PrilohyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Prilohy>
    {
        public PrilohyConfiguration()
            : this("dbo")
        {
        }

        public PrilohyConfiguration(string schema)
        {
            ToTable("Prilohy", schema);
            HasKey(x => new { x.Id, x.Priloha, x.IdUbytovani });

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Priloha).HasColumnName(@"Priloha").HasColumnType("image").IsRequired().HasMaxLength(2147483647).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdUbytovani).HasColumnName(@"ID_Ubytovani").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Ubytovani).WithMany(b => b.Prilohy).HasForeignKey(c => c.IdUbytovani).WillCascadeOnDelete(false); // FK_Prilohy_Ubytovani
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
