// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Rezervace
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class Rezervace
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid IdZajezdu { get; set; } // ID_Zajezdu
        public System.DateTime DatumVytvoreni { get; set; } // Datum_vytvoreni
        public System.Guid IdZakaznika { get; set; } // ID_Zakaznika
        public System.Guid? IdPojisteni { get; set; } // ID_Pojisteni

        // Foreign keys

        /// <summary>
        /// Parent Pojisteni pointed by [Rezervace].([IdPojisteni]) (FK_Rezervace_Pojisteni)
        /// </summary>
        public virtual Pojisteni Pojisteni { get; set; } // FK_Rezervace_Pojisteni
        /// <summary>
        /// Parent Zajezdy pointed by [Rezervace].([IdZajezdu]) (FK_Rezervace_Zajezdy)
        /// </summary>
        public virtual Zajezdy Zajezdy { get; set; } // FK_Rezervace_Zajezdy
        /// <summary>
        /// Parent Zakaznici pointed by [Rezervace].([IdZakaznika]) (FK_Rezervace_Zakaznici)
        /// </summary>
        public virtual Zakaznici Zakaznici { get; set; } // FK_Rezervace_Zakaznici

        public Rezervace()
        {
            Id = System.Guid.NewGuid();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
