// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Rezervace
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class RezervaceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Rezervace>
    {
        public RezervaceConfiguration()
            : this("dbo")
        {
        }

        public RezervaceConfiguration(string schema)
        {
            ToTable("Rezervace", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdZajezdu).HasColumnName(@"ID_Zajezdu").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.DatumVytvoreni).HasColumnName(@"Datum_vytvoreni").HasColumnType("datetime2").IsRequired();
            Property(x => x.IdZakaznika).HasColumnName(@"ID_Zakaznika").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IdPojisteni).HasColumnName(@"ID_Pojisteni").HasColumnType("uniqueidentifier").IsOptional();

            // Foreign keys
            HasOptional(a => a.Pojisteni).WithMany(b => b.Rezervace).HasForeignKey(c => c.IdPojisteni).WillCascadeOnDelete(false); // FK_Rezervace_Pojisteni
            HasRequired(a => a.Zajezdy).WithMany(b => b.Rezervace).HasForeignKey(c => c.IdZajezdu).WillCascadeOnDelete(false); // FK_Rezervace_Zajezdy
            HasRequired(a => a.Zakaznici).WithMany(b => b.Rezervace).HasForeignKey(c => c.IdZakaznika).WillCascadeOnDelete(false); // FK_Rezervace_Zakaznici
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
