// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Typ_zajezdu
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class TypZajezdu
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public string Popis { get; set; } // Popis

        // Reverse navigation

        /// <summary>
        /// Child VazTZajezdTypZajezdu where [VazT_Zajezd_TypZajezdu].[ID_Typ_zajezdu] point to this entity (FK_VazT_Zajezd_TypZajezdu_Typ_zajezdu)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<VazTZajezdTypZajezdu> VazTZajezdTypZajezdu { get; set; } // VazT_Zajezd_TypZajezdu.FK_VazT_Zajezd_TypZajezdu_Typ_zajezdu

        public TypZajezdu()
        {
            Id = System.Guid.NewGuid();
            VazTZajezdTypZajezdu = new System.Collections.Generic.List<VazTZajezdTypZajezdu>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
