// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Ubytovani
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class Ubytovani
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid? IdAdresa { get; set; } // ID_Adresa
        public System.Guid IdTypUbytovani { get; set; } // ID_Typ_ubytovani
        public int? PocetHvezd { get; set; } // Pocet_hvezd
        public string Popis { get; set; } // Popis

        // Reverse navigation

        /// <summary>
        /// Child Pokoje where [Pokoje].[ID_Ubytovani] point to this entity (FK_Pokoje_Ubytovani)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Pokoje> Pokoje { get; set; } // Pokoje.FK_Pokoje_Ubytovani
        /// <summary>
        /// Child Prilohy where [Prilohy].[ID_Ubytovani] point to this entity (FK_Prilohy_Ubytovani)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Prilohy> Prilohy { get; set; } // Prilohy.FK_Prilohy_Ubytovani
        /// <summary>
        /// Child Zajezdy where [Zajezdy].[ID_Ubytovani] point to this entity (FK_Zajezdy_Typ_ubytovani)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Zajezdy> Zajezdy { get; set; } // Zajezdy.FK_Zajezdy_Typ_ubytovani

        // Foreign keys

        /// <summary>
        /// Parent Adresa pointed by [Ubytovani].([Id]) (FK_Ubytovani_Adresa)
        /// </summary>
        public virtual Adresa Adresa { get; set; } // FK_Ubytovani_Adresa
        /// <summary>
        /// Parent TypUbytovani pointed by [Ubytovani].([IdTypUbytovani]) (FK_Ubytovani_Typ_ubytovani)
        /// </summary>
        public virtual TypUbytovani TypUbytovani { get; set; } // FK_Ubytovani_Typ_ubytovani

        public Ubytovani()
        {
            Pokoje = new System.Collections.Generic.List<Pokoje>();
            Prilohy = new System.Collections.Generic.List<Prilohy>();
            Zajezdy = new System.Collections.Generic.List<Zajezdy>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
