// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Ubytovani
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class UbytovaniConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ubytovani>
    {
        public UbytovaniConfiguration()
            : this("dbo")
        {
        }

        public UbytovaniConfiguration(string schema)
        {
            ToTable("Ubytovani", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdAdresa).HasColumnName(@"ID_Adresa").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.IdTypUbytovani).HasColumnName(@"ID_Typ_ubytovani").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.PocetHvezd).HasColumnName(@"Pocet_hvezd").HasColumnType("int").IsOptional();
            Property(x => x.Popis).HasColumnName(@"Popis").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.Nazev).HasColumnName(@"Nazev").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);

            // Foreign keys
            HasOptional(a => a.Adresa).WithMany(b => b.Ubytovani).HasForeignKey(c => c.IdAdresa).WillCascadeOnDelete(false); // FK_Ubytovani_Adresa
            HasRequired(a => a.TypUbytovani).WithMany(b => b.Ubytovani).HasForeignKey(c => c.IdTypUbytovani).WillCascadeOnDelete(false); // FK_Ubytovani_Typ_ubytovani
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
