// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // VazT_Zakaznik_Zajezd
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class VazTZakaznikZajezd
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid IdZakaznik { get; set; } // ID_Zakaznik
        public System.Guid IdZajezd { get; set; } // ID_Zajezd

        // Foreign keys

        /// <summary>
        /// Parent Zajezdy pointed by [VazT_Zakaznik_Zajezd].([IdZajezd]) (FK_VazT_Zakaznik_Zajezd_Zajezdy)
        /// </summary>
        public virtual Zajezdy Zajezdy { get; set; } // FK_VazT_Zakaznik_Zajezd_Zajezdy
        /// <summary>
        /// Parent Zakaznici pointed by [VazT_Zakaznik_Zajezd].([IdZakaznik]) (FK_VazT_Zakaznik_Zajezd_Zakaznici)
        /// </summary>
        public virtual Zakaznici Zakaznici { get; set; } // FK_VazT_Zakaznik_Zajezd_Zakaznici

        public VazTZakaznikZajezd()
        {
            Id = System.Guid.NewGuid();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
