// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // VazT_Zajezd_TypZajezdu
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class VazTZajezdTypZajezdu
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid IdZajezdy { get; set; } // ID_Zajezdy (Primary key)
        public System.Guid IdTypZajezdu { get; set; } // ID_Typ_zajezdu (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent TypZajezdu pointed by [VazT_Zajezd_TypZajezdu].([IdTypZajezdu]) (FK_VazT_Zajezd_TypZajezdu_Typ_zajezdu)
        /// </summary>
        public virtual TypZajezdu TypZajezdu { get; set; } // FK_VazT_Zajezd_TypZajezdu_Typ_zajezdu
        /// <summary>
        /// Parent Zajezdy pointed by [VazT_Zajezd_TypZajezdu].([IdZajezdy]) (FK_VazT_Zajezd_TypZajezdu_Zajezdy)
        /// </summary>
        public virtual Zajezdy Zajezdy { get; set; } // FK_VazT_Zajezd_TypZajezdu_Zajezdy

        public VazTZajezdTypZajezdu()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
