// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Zajezdy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class Zajezdy
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid IdTypZajezdu { get; set; } // ID_Typ_zajezdu
        public System.Guid IdDestinace { get; set; } // ID_Destinace
        public System.Guid IdDoprava { get; set; } // ID_Doprava
        public System.Guid IdStravovani { get; set; } // ID_Stravovani
        public System.Guid IdTypUbytovani { get; set; } // ID_Typ_ubytovani
        public System.Guid IdKategorie { get; set; } // ID_Kategorie
        public System.DateTime DatumOd { get; set; } // Datum_od
        public int DelkaPobytu { get; set; } // Delka_pobytu
        public decimal Cena { get; set; } // Cena
        public int Kapacita { get; set; } // Kapacita
        public System.DateTime? DatumZruseni { get; set; } // Datum_zruseni
        public string Popis { get; set; } // Popis

        // Reverse navigation

        /// <summary>
        /// Child Rezervace where [Rezervace].[ID_Zajezdu] point to this entity (FK_Rezervace_Zajezdy)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Rezervace> Rezervace { get; set; } // Rezervace.FK_Rezervace_Zajezdy
        /// <summary>
        /// Child VazTZakaznikZajezd where [VazT_Zakaznik_Zajezd].[ID_Zajezd] point to this entity (FK_VazT_Zakaznik_Zajezd_Zajezdy)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<VazTZakaznikZajezd> VazTZakaznikZajezd { get; set; } // VazT_Zakaznik_Zajezd.FK_VazT_Zakaznik_Zajezd_Zajezdy

        // Foreign keys

        /// <summary>
        /// Parent Destinace pointed by [Zajezdy].([IdDestinace]) (FK_Zajezdy_Destinace)
        /// </summary>
        public virtual Destinace Destinace { get; set; } // FK_Zajezdy_Destinace
        /// <summary>
        /// Parent Doprava pointed by [Zajezdy].([IdDoprava]) (FK_Zajezdy_Doprava)
        /// </summary>
        public virtual Doprava Doprava { get; set; } // FK_Zajezdy_Doprava
        /// <summary>
        /// Parent Kategorie pointed by [Zajezdy].([IdKategorie]) (FK_Zajezdy_Kategorie)
        /// </summary>
        public virtual Kategorie Kategorie { get; set; } // FK_Zajezdy_Kategorie
        /// <summary>
        /// Parent Stravovani pointed by [Zajezdy].([IdStravovani]) (FK_Zajezdy_Stravovani)
        /// </summary>
        public virtual Stravovani Stravovani { get; set; } // FK_Zajezdy_Stravovani
        /// <summary>
        /// Parent TypUbytovani pointed by [Zajezdy].([IdTypUbytovani]) (FK_Zajezdy_Typ_ubytovani)
        /// </summary>
        public virtual TypUbytovani TypUbytovani { get; set; } // FK_Zajezdy_Typ_ubytovani
        /// <summary>
        /// Parent TypZajezdu pointed by [Zajezdy].([IdTypZajezdu]) (FK_Zajezdy_Typ_zajezdu)
        /// </summary>
        public virtual TypZajezdu TypZajezdu { get; set; } // FK_Zajezdy_Typ_zajezdu

        public Zajezdy()
        {
            Id = System.Guid.NewGuid();
            Rezervace = new System.Collections.Generic.List<Rezervace>();
            VazTZakaznikZajezd = new System.Collections.Generic.List<VazTZakaznikZajezd>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
