// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Zajezdy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class ZajezdyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Zajezdy>
    {
        public ZajezdyConfiguration()
            : this("dbo")
        {
        }

        public ZajezdyConfiguration(string schema)
        {
            ToTable("Zajezdy", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IdTypZajezdu).HasColumnName(@"ID_Typ_zajezdu").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IdDestinace).HasColumnName(@"ID_Destinace").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IdDoprava).HasColumnName(@"ID_Doprava").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IdStravovani).HasColumnName(@"ID_Stravovani").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IdUbytovani).HasColumnName(@"ID_Ubytovani").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IdKategorie).HasColumnName(@"ID_Kategorie").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.DatumOd).HasColumnName(@"Datum_od").HasColumnType("datetime2").IsRequired();
            Property(x => x.DelkaPobytu).HasColumnName(@"Delka_pobytu").HasColumnType("int").IsRequired();
            Property(x => x.Cena).HasColumnName(@"Cena").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Kapacita).HasColumnName(@"Kapacita").HasColumnType("int").IsRequired();
            Property(x => x.DatumZruseni).HasColumnName(@"Datum_zruseni").HasColumnType("datetime2").IsOptional();
            Property(x => x.Popis).HasColumnName(@"Popis").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Destinace).WithMany(b => b.Zajezdy).HasForeignKey(c => c.IdDestinace).WillCascadeOnDelete(false); // FK_Zajezdy_Destinace
            HasRequired(a => a.Doprava).WithMany(b => b.Zajezdy).HasForeignKey(c => c.IdDoprava).WillCascadeOnDelete(false); // FK_Zajezdy_Doprava
            HasRequired(a => a.Kategorie).WithMany(b => b.Zajezdy).HasForeignKey(c => c.IdKategorie).WillCascadeOnDelete(false); // FK_Zajezdy_Kategorie
            HasRequired(a => a.Stravovani).WithMany(b => b.Zajezdy).HasForeignKey(c => c.IdStravovani).WillCascadeOnDelete(false); // FK_Zajezdy_Stravovani
            HasRequired(a => a.TypZajezdu).WithMany(b => b.Zajezdy).HasForeignKey(c => c.IdTypZajezdu).WillCascadeOnDelete(false); // FK_Zajezdy_Typ_zajezdu
            HasRequired(a => a.Ubytovani).WithMany(b => b.Zajezdy).HasForeignKey(c => c.IdUbytovani).WillCascadeOnDelete(false); // FK_Zajezdy_Typ_ubytovani
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
