// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace IS_BRACES.Models
{

    // Zakaznici
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class ZakazniciConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Zakaznici>
    {
        public ZakazniciConfiguration()
            : this("dbo")
        {
        }

        public ZakazniciConfiguration(string schema)
        {
            ToTable("Zakaznici", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Jmeno).HasColumnName(@"Jmeno").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Prijmeni).HasColumnName(@"Prijmeni").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.IdBydliste).HasColumnName(@"ID_Bydliste").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.IdKontaktniUdaje).HasColumnName(@"ID_Kontaktni_udaje").HasColumnType("uniqueidentifier").IsOptional();

            // Foreign keys
            HasOptional(a => a.Adresa).WithMany(b => b.Zakaznici).HasForeignKey(c => c.IdBydliste).WillCascadeOnDelete(false); // FK_Zakaznici_Adresa
            HasOptional(a => a.KontaktniUdaje).WithMany(b => b.Zakaznici).HasForeignKey(c => c.IdKontaktniUdaje).WillCascadeOnDelete(false); // FK_Zakaznici_Kontaktni_udaje
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
